#!/bin/bash
set -euo pipefail

usage()
{
    exec 1>&2
    echo "Usage: $0 rejection | smc | sweep"
    exit 2
}

[ $# -lt 1 ] && usage

method=$1
shift

case "$method" in
    rejection)
        exec rejection-mpi "$@"
        ;;
    smc)
        exec smc-mpi "$@"
        ;;
    sweep)
        exec sweep-mpi "$@"
        ;;
    *)
        usage
        ;;
esac
